export const SET_WINNERS_DATA = 'GET_WINNERS_DATA';
export const FETCH_WINNERS_DATA_FAILED = 'FETCH_WINNERS_DATA_FAILED';

export const SET_GAME_SETTINGS_DATA = 'SET_GAME_SETTINGS_DATA';
export const FETCH_GAME_SETTINGS_FAILED = 'FETCH_GAME_SETTINGS_FAILED';